enum scope_type {
	SCOPE_CONST,
	SCOPE_INPUT,
	SCOPE_OUTPUT,
	SCOPE_GLOBAL,
	SCOPE_LOCAL
};

enum quad_type {
	AFFEC,
	AFFEC_UNARY_MINUS,
	AFFEC_UNARY_NOT,
	AFFEC_BINARY_PLUS,
	AFFEC_BINARY_MINUS,
	AFFEC_BINARY_MULT,
	AFFEC_BINARY_DIV,
	AFFEC_BINARY_OR,
	AFFEC_BINARY_AND,
	BRANCHMENT_UNCOND,
	BRANCHMENT_COND_EQ,
	BRANCHMENT_COND_NEQ,
	BRANCHMENT_COND_LT,
	BRANCHMENT_COND_LTEQ,
	BRANCHMENT_COND_GT,
	BRANCHMENT_COND_GTEQ,
	PROC_PARAM,
	PROC_CALL,
	TAB_LEFT,
	TAB_RIGHT
};

#define TRUE 1
#define FALSE 0

